### ISSUE TITLE
Runtime safety - No checks whether message type extends custom trait associated with our serializer

### ISSUE THREAD

**Issue by MarconZet** [VirtusLab/akka-safer-serializer#8] opened 2021-04-19 12:56 UTC
Akka determines what serialiser to use on what message based on the class of the message and its supertype. If a supertype is declared incorrectly, unexpected behaviour may occur.

**Comment by PawelLipski** [comment] 2021-04-24 19:21
Hmmm could you provide a minimal repro? Esp. what you mean by _supertype is declared incorrectly_

**Comment by PawelLipski** [comment] 2021-04-28 15:42
(@MarconZet bump)

**Comment by PawelLipski** [comment] 2021-05-04 12:11
Duplicate of #5

**Closed by PawelLipski** 2021-05-04 12:11 UTC
Labels: duplicate, soundness
